<Project>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Orleans.Server" Version="$(OrleansVersion)" />
    <PackageVersion Include="Microsoft.Orleans.Streaming" Version="$(OrleansVersion)" />
    <PackageVersion Include="Microsoft.Orleans.Streaming.EventHubs" Version="$(OrleansVersion)" />
  </ItemGroup>
</Project>
